/*
 * Copyright (c) 2024 F&S Elektronik Systeme GmbH
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include <board/pinmux.h>

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitLpuartOSM(void)
{
	/* UART-B*/
	IOMUXC_SetPinMux(IOMUXC_PTA2_LPUART0_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA2_LPUART0_TX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK |
				IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA3_LPUART0_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA3_LPUART0_RX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK |
				IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA16_LPUART0_CTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA16_LPUART0_CTS_B,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK |
				IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA17_LPUART0_RTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA17_LPUART0_RTS_B,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK |
				IOMUXC_PCR_DSE_MASK);

	/* UART-C */
	IOMUXC_SetPinMux(IOMUXC_PTB2_LPUART2_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB2_LPUART2_TX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK |
				IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB3_LPUART2_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB3_LPUART2_RX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK);

	/* UART-D */
	IOMUXC_SetPinMux(IOMUXC_PTA10_LPUART1_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA10_LPUART1_TX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA11_LPUART1_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA11_LPUART1_RX,
				IOMUXC_PCR_PE_MASK |
				IOMUXC_PCR_PS_MASK);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitLpuartArmStone(void)
{
	/* UART-B*/
	IOMUXC_SetPinMux(IOMUXC_PTA2_LPUART0_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA2_LPUART0_TX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA3_LPUART0_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA3_LPUART0_RX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA16_LPUART0_CTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA16_LPUART0_CTS_B,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA17_LPUART0_RTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA17_LPUART0_RTS_B,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);

	/* UART-E */
	IOMUXC_SetPinMux(IOMUXC_PTB2_LPUART2_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB2_LPUART2_TX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB3_LPUART2_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB3_LPUART2_RX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitLpuartPCore(void)
{
	/* UART-B*/
	IOMUXC_SetPinMux(IOMUXC_PTA2_LPUART0_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA2_LPUART0_TX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA3_LPUART0_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA3_LPUART0_RX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA16_LPUART0_CTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA16_LPUART0_CTS_B,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA17_LPUART0_RTS_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA17_LPUART0_RTS_B,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);

	/* UART-D */
	IOMUXC_SetPinMux(IOMUXC_PTA10_LPUART1_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA10_LPUART1_TX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA11_LPUART1_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA11_LPUART1_RX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitLpuartPins(struct board_descr *bdescr) {
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitLpuartPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitLpuartOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitLpuartArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitI2cOSM(void)
{
	/* I2C_B */
	IOMUXC_SetPinMux(IOMUXC_PTA14_I3C0_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA14_I3C0_SCL,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA15_I3C0_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA15_I3C0_SDA,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);

	/* I2C_CAM */
	IOMUXC_SetPinMux(IOMUXC_PTB0_LPI2C2_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB0_LPI2C2_SCL,
		IOMUXC_PCR_ODE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB1_LPI2C2_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB1_LPI2C2_SDA,
		IOMUXC_PCR_ODE_MASK);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitI2cArmStone(void)
{
	/* I2C_E */
	IOMUXC_SetPinMux(IOMUXC_PTA14_I3C0_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA14_I3C0_SCL,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA15_I3C0_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA15_I3C0_SDA,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);
}
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitI2cPCore(void)
{
	/* I2C_B */
	IOMUXC_SetPinMux(IOMUXC_PTA0_LPI2C0_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA0_LPI2C0_SCL,
		IOMUXC_PCR_ODE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA1_LPI2C0_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA1_LPI2C0_SDA,
		IOMUXC_PCR_ODE_MASK);
	/* I2C_RTD*/
	IOMUXC_SetPinMux(IOMUXC_PTA14_I3C0_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA14_I3C0_SCL,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA15_I3C0_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA15_I3C0_SDA,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_SRE_MASK);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitI2cPins(struct board_descr *bdescr) {
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitI2cPCore();
			break;
#endif
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitI2cOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitI2cArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

static void BOARD_InitPmicI2cPins(void) {
	IOMUXC_SetPinMux(IOMUXC_PTB10_PMIC0_SDA, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB10_PMIC0_SDA,
		IOMUXC_PCR_ODE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB11_PMIC0_SCL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB11_PMIC0_SCL,
		IOMUXC_PCR_ODE_MASK);
}

static void BOARD_InitPmicModePins(void) {
	IOMUXC_SetPinMux(IOMUXC_PTB7_PMIC0_MODE2, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB7_PMIC0_MODE2,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB8_PMIC0_MODE1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB8_PMIC0_MODE1,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB9_PMIC0_MODE0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTB9_PMIC0_MODE0,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitI2sOSM(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTC10_I2S0_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC10_I2S0_MCLK,
		IOMUXC_PCR_OBE_MASK |
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC9_I2S0_TX_FS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC9_I2S0_TX_FS,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC8_I2S0_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC8_I2S0_TX_BCLK,
		IOMUXC_PCR_DSE_MASK);

	/* I2S_A */
	IOMUXC_SetPinMux(IOMUXC_PTC4_I2S0_RXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC4_I2S0_RXD0,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC7_I2S0_TXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC7_I2S0_TXD0,
		IOMUXC_PCR_DSE_MASK);

	/* I2S_B */
	IOMUXC_SetPinMux(IOMUXC_PTC5_I2S0_RXD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC5_I2S0_RXD1,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC6_I2S0_TXD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC6_I2S0_TXD1,
		IOMUXC_PCR_DSE_MASK);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitI2sArmStone(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTC10_I2S0_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC10_I2S0_MCLK,
		IOMUXC_PCR_OBE_MASK |
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC9_I2S0_TX_FS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC9_I2S0_TX_FS,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC8_I2S0_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC8_I2S0_TX_BCLK,
		IOMUXC_PCR_DSE_MASK);

	/* I2S_A */
	IOMUXC_SetPinMux(IOMUXC_PTC4_I2S0_RXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC4_I2S0_RXD0,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC7_I2S0_TXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC7_I2S0_TXD0,
		IOMUXC_PCR_DSE_MASK);
}
#endif

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitI2sPCore(void)
{
	/* Audio Intern */
	IOMUXC_SetPinMux(IOMUXC_PTC10_I2S0_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC10_I2S0_MCLK,
		IOMUXC_PCR_OBE_MASK |
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC9_I2S0_TX_FS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC9_I2S0_TX_FS,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC8_I2S0_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC8_I2S0_TX_BCLK,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC4_I2S0_RXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC4_I2S0_RXD0,
		IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC7_I2S0_TXD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC7_I2S0_TXD0,
		IOMUXC_PCR_DSE_MASK);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitI2sPins(struct board_descr *bdescr) {
		switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
			case BT_PICOCOREMX8ULP:
				BOARD_InitI2sPCore();
				break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
			case BT_OSMSFMX8ULP:
				BOARD_InitI2sOSM();
				break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
			case BT_ARMSTONEMX8ULP:
				BOARD_InitI2sArmStone();
				break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
			default:
				break;
		}
}

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitTpmOSM()
{
	/* PWM 1 */
	IOMUXC_SetPinMux(IOMUXC_PTA9_TPM1_CH1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA9_TPM1_CH1,
		IOMUXC_PCR_DSE_MASK);

	/* PWM_2 */
	IOMUXC_SetPinMux(IOMUXC_PTA18_TPM0_CH3, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA18_TPM0_CH3,
		IOMUXC_PCR_DSE_MASK);

	/* PWM_3 */
	IOMUXC_SetPinMux(IOMUXC_PTC1_TPM2_CH0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC1_TPM2_CH0,
		IOMUXC_PCR_DSE_MASK);

	/* PWM_4 */
	IOMUXC_SetPinMux(IOMUXC_PTC2_TPM2_CH1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC2_TPM2_CH1,
		IOMUXC_PCR_DSE_MASK);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitTpmArmStone(void)
{
	/* PWM 1 */
	IOMUXC_SetPinMux(IOMUXC_PTA9_TPM1_CH1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA9_TPM1_CH1,
		IOMUXC_PCR_DSE_MASK);

	/* PWM 2 */
	IOMUXC_SetPinMux(IOMUXC_PTC2_TPM2_CH1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC2_TPM2_CH1,
		IOMUXC_PCR_DSE_MASK);

	/* PWM 3 */
	IOMUXC_SetPinMux(IOMUXC_PTC12_TPM3_CH0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_TPM3_CH0,
		IOMUXC_PCR_DSE_MASK);
}
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitTpmPCore(void)
{
	/* PWM */
	IOMUXC_SetPinMux(IOMUXC_PTC1_TPM2_CH0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC1_TPM2_CH0,
		IOMUXC_PCR_DSE_MASK);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitTpmPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitTpmPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitTpmOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitTpmArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitIOPCore(struct board_descr *bdescr)
{
	uint32_t bfeatures = bdescr->bfeatures;

	/* PTA */
	IOMUXC_SetPinMux(IOMUXC_PTA8_PTA8, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA8_PTA8,
		IOMUXC_PCR_PE_MASK);
	/* I2C_RTD_IRQ */
	IOMUXC_SetPinMux(IOMUXC_PTA9_PTA9, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA9_PTA9,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	/* I2C_B_IRQ */
	IOMUXC_SetPinMux(IOMUXC_PTA18_PTA18, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA18_PTA18,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	/* SPI_B_CS0 */
	IOMUXC_SetPinMux(IOMUXC_PTA19_PTA19, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA19_PTA19,
		IOMUXC_PCR_PE_MASK);
	/* PMIC_IRQ */
	IOMUXC_SetPinMux(IOMUXC_PTA24_PTA24, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA24_PTA24,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);

	/* PTB */
	IOMUXC_SetPinMux(IOMUXC_PTB0_PTB0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB0_PTB0,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB1_PTB1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB1_PTB1,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB2_PTB2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB2_PTB2,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB3_PTB3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB3_PTB3,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB4_PTB4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB4_PTB4,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB5_PTB5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB5_PTB5,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB6_PTB6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB6_PTB6,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB12_PTB12, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB12_PTB12,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB13_PTB13, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB13_PTB13,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB14_PTB14, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB14_PTB14,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB15_PTB15, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB15_PTB15,
		IOMUXC_PCR_PE_MASK);

	/* PTC */
	IOMUXC_SetPinMux(IOMUXC_PTC0_PTC0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC0_PTC0,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC2_PTC2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC2_PTC2,
		IOMUXC_PCR_PE_MASK);
	/* LVDS_CONV_RST */
	IOMUXC_SetPinMux(IOMUXC_PTC3_PTC3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC3_PTC3,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC5_PTC5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC5_PTC5,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC6_PTC6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC6_PTC6,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC11_PTC11, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC11_PTC11,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC23_PTC23, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC23_PTC23,
		IOMUXC_PCR_PE_MASK);

	/* If QSPI is not used, GPIO is used */
	if (!!(bfeatures & (FEAT_QSPI_FLASH | FEAT_QSPI_PSRAM)))
		return;

	IOMUXC_SetPinMux(IOMUXC_PTC12_PTC12, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_PTC12,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC13_PTC13, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC13_PTC13,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_PTC14, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_PTC14,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_PTC15, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_PTC15,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_PTC16, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_PTC16,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC17_PTC17, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC17_PTC17,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC18_PTC18, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC18_PTC18,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC19_PTC19, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC19_PTC19,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC20_PTC20, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC20_PTC20,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC21_PTC21, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC21_PTC21,
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC22_PTC22, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC22_PTC22,
		IOMUXC_PCR_PE_MASK);

	return;
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitIOOSM()
{
	IOMUXC_SetPinMux(IOMUXC_PTA0_PTA0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA0_PTA0, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA24_PTA24, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA24_PTA24, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA1_PTA1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTA1_PTA1,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB5_PTB5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB5_PTB5, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB6_PTB6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB6_PTB6, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB13_PTB13, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB13_PTB13, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTB14_PTB14, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB14_PTB14, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC0_PTC0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC0_PTC0, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC3_PTC3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC3_PTC3, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC11_PTC11, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC11_PTC11, IOMUXC_PCR_PE_MASK);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitIOArmStone()
{
	IOMUXC_SetPinMux(IOMUXC_PTB4_PTB4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTB4_PTB4,
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC0_PTC0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC0_PTC0, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_PTC14, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_PTC14, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_PTC15, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_PTC15, IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_PTC16, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_PTC16, IOMUXC_PCR_PE_MASK);
}
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

static void BOARD_InitIOPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitIOPCore(bdescr);
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitIOOSM();
			break;
#endif
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitIOArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitFLEXSPIOSM()
{
#if defined(OSM_USE_FLEXSPI0)
	IOMUXC_SetPinMux(IOMUXC_PTC12_FLEXSPI0_B_DQS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_FLEXSPI0_B_DQS,
			IOMUXC_PCR_DSE_MASK |
			IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC13_FLEXSPI0_B_DATA7, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC13_FLEXSPI0_B_DATA7, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_FLEXSPI0_B_DATA6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_FLEXSPI0_B_DATA6, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_FLEXSPI0_B_DATA5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_FLEXSPI0_B_DATA5, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_FLEXSPI0_B_DATA4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_FLEXSPI0_B_DATA4, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC17_FLEXSPI0_B_SS0_B, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC17_FLEXSPI0_B_SS0_B, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC18_FLEXSPI0_B_SCLK, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC18_FLEXSPI0_B_SCLK, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC19_FLEXSPI0_B_DATA3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC19_FLEXSPI0_B_DATA3, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC20_FLEXSPI0_B_DATA2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC20_FLEXSPI0_B_DATA2, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC21_FLEXSPI0_B_DATA1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC21_FLEXSPI0_B_DATA1, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC22_FLEXSPI0_B_DATA0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC22_FLEXSPI0_B_DATA0, IOMUXC_PCR_DSE_MASK);
#else
	IOMUXC_SetPinMux(IOMUXC_PTC12_FLEXSPI1_A_DQS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_FLEXSPI1_A_DQS,
			IOMUXC_PCR_DSE_MASK |
			IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC13_FLEXSPI1_A_DATA7, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC13_FLEXSPI1_A_DATA7, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_FLEXSPI1_A_DATA6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_FLEXSPI1_A_DATA6, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_FLEXSPI1_A_DATA5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_FLEXSPI1_A_DATA5, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_FLEXSPI1_A_DATA4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_FLEXSPI1_A_DATA4, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC17_FLEXSPI1_A_SS0_B, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC17_FLEXSPI1_A_SS0_B, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC18_FLEXSPI1_B_SCLK, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC18_FLEXSPI1_B_SCLK, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC19_FLEXSPI1_B_DATA3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC19_FLEXSPI1_B_DATA3, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC20_FLEXSPI1_B_DATA2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC20_FLEXSPI1_B_DATA2, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC21_FLEXSPI1_B_DATA1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC21_FLEXSPI1_B_DATA1, IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC22_FLEXSPI1_B_DATA0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC22_FLEXSPI1_B_DATA0, IOMUXC_PCR_DSE_MASK);
#endif
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitFLEXSPIPCore()
{
#if defined(PCore_USE_FLEXSPI0)
	IOMUXC_SetPinMux(IOMUXC_PTC12_FLEXSPI0_B_DQS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_FLEXSPI0_B_DQS,
			IOMUXC_PCR_DSE_MASK |
			IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC13_FLEXSPI0_B_DATA7, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC13_FLEXSPI0_B_DATA7,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_FLEXSPI0_B_DATA6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_FLEXSPI0_B_DATA6,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_FLEXSPI0_B_DATA5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_FLEXSPI0_B_DATA5,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_FLEXSPI0_B_DATA4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_FLEXSPI0_B_DATA4,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC17_FLEXSPI0_B_SS0_B, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC17_FLEXSPI0_B_SS0_B,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC18_FLEXSPI0_B_SCLK, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC18_FLEXSPI0_B_SCLK,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC19_FLEXSPI0_B_DATA3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC19_FLEXSPI0_B_DATA3,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC20_FLEXSPI0_B_DATA2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC20_FLEXSPI0_B_DATA2,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC21_FLEXSPI0_B_DATA1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC21_FLEXSPI0_B_DATA1,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC22_FLEXSPI0_B_DATA0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC22_FLEXSPI0_B_DATA0,
			IOMUXC_PCR_DSE_MASK);
#else
	IOMUXC_SetPinMux(IOMUXC_PTC12_FLEXSPI1_A_DQS, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTC12_FLEXSPI1_A_DQS,
			IOMUXC_PCR_DSE_MASK |
			IOMUXC_PCR_PE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC13_FLEXSPI1_A_DATA7, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC13_FLEXSPI1_A_DATA7,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC14_FLEXSPI1_A_DATA6, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC14_FLEXSPI1_A_DATA6,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC15_FLEXSPI1_A_DATA5, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC15_FLEXSPI1_A_DATA5,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC16_FLEXSPI1_A_DATA4, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC16_FLEXSPI1_A_DATA4,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC17_FLEXSPI1_A_SS0_B, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC17_FLEXSPI1_A_SS0_B,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC18_FLEXSPI1_B_SCLK, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC18_FLEXSPI1_B_SCLK,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC19_FLEXSPI1_B_DATA3, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC19_FLEXSPI1_B_DATA3,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC20_FLEXSPI1_B_DATA2, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC20_FLEXSPI1_B_DATA2,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC21_FLEXSPI1_B_DATA1, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC21_FLEXSPI1_B_DATA1,
			IOMUXC_PCR_DSE_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTC22_FLEXSPI1_B_DATA0, 0);
	IOMUXC_SetPinConfig(IOMUXC_PTC22_FLEXSPI1_B_DATA0,
			IOMUXC_PCR_DSE_MASK);
#endif
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitFLEXSPIPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitFLEXSPIPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitFLEXSPIOSM();
			break;
#endif
		default:
			break;
	}
}

void BOARD_InitBootPins_pre(void)
{
	BOARD_InitPmicI2cPins();
	BOARD_InitPmicModePins();
}

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
void BOARD_InitJTAGPCore(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA21_JTAG0_TDO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA21_JTAG0_TDO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA22_JTAG0_TDI, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA22_JTAG0_TDI,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif

#ifdef CONFIG_BOARD_OSMSFMX8ULP
void BOARD_InitJTAGOSM(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA19_JTAG0_TRST_B, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA19_JTAG0_TRST_B,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA21_JTAG0_TDO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA21_JTAG0_TDO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA22_JTAG0_TDI, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA22_JTAG0_TDI,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
void BOARD_InitJTAGArmStone(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA20_JTAG0_TMS_SWD0_DIO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA21_JTAG0_TDO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA21_JTAG0_TDO,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA22_JTAG0_TDI, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA22_JTAG0_TDI,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
	IOMUXC_SetPinMux(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA23_JTAG0_TCLK_SWD0_CLK,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

void BOARD_InitJTAGPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitJTAGPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitJTAGOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitJTAGArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitSPIPCore(void)
{
	/* SPI_B */
	IOMUXC_SetPinMux(IOMUXC_PTA4_LPSPI0_SIN, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA4_LPSPI0_SIN,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA5_LPSPI0_SOUT, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA5_LPSPI0_SOUT,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA6_LPSPI0_SCK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA6_LPSPI0_SCK,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	/* chipselect as GPIO */
	IOMUXC_SetPinMux(IOMUXC_PTA19_PTA19, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA19_PTA19,
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitSPIOSM(void)
{
	/* SPI_B */
	IOMUXC_SetPinMux(IOMUXC_PTA4_LPSPI0_SIN, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA4_LPSPI0_SIN,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA5_LPSPI0_SOUT, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA5_LPSPI0_SOUT,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA6_LPSPI0_SCK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA6_LPSPI0_SCK,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA7_LPSPI0_PCS0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA7_LPSPI0_PCS0,
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	/* chipselect2 as GPIO */
	IOMUXC_SetPinMux(IOMUXC_PTA8_PTA8, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA8_PTA8,
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitSPIArmStone(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA4_LPSPI0_SIN, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA4_LPSPI0_SIN,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA5_LPSPI0_SOUT, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA5_LPSPI0_SOUT,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA6_LPSPI0_SCK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA6_LPSPI0_SCK,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
	IOMUXC_SetPinMux(IOMUXC_PTA7_LPSPI0_PCS0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA7_LPSPI0_PCS0,
		IOMUXC_PCR_DSE_MASK |
		IOMUXC_PCR_PS_MASK |
		IOMUXC_PCR_PE_MASK
	);
}
#endif

static void BOARD_InitSPIPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitSPIPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitSPIOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitSPIArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitWDOGPCore(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA7_WDOG1_RST, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA7_WDOG1_RST,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK);
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

static void BOARD_InitWDOGPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitWDOGPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
		default:
			break;
	}
}

#ifdef CONFIG_BOARD_PICOCOREMX8ULP
static void BOARD_InitCANPCore(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA12_CAN0_TX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA12_CAN0_TX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK );
	IOMUXC_SetPinMux(IOMUXC_PTA13_CAN0_RX, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PTA13_CAN0_RX,
		IOMUXC_PCR_PE_MASK |
		IOMUXC_PCR_PS_MASK );
}
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */

#ifdef CONFIG_BOARD_OSMSFMX8ULP
static void BOARD_InitCANOSM(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA12_CAN0_TX, 0U);
	IOMUXC_SetPinMux(IOMUXC_PTA13_CAN0_RX, 0U);
}
#endif /* CONFIG_BOARD_OSMSFMX8ULP */

#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
static void BOARD_InitCANArmStone(void)
{
	IOMUXC_SetPinMux(IOMUXC_PTA12_CAN0_TX, 0U);
	IOMUXC_SetPinMux(IOMUXC_PTA13_CAN0_RX, 0U);
}
#endif

static void BOARD_InitCANPins(struct board_descr *bdescr)
{
	switch(bdescr->btype) {
#ifdef CONFIG_BOARD_PICOCOREMX8ULP
		case BT_PICOCOREMX8ULP:
			BOARD_InitCANPCore();
			break;
#endif /* CONFIG_BOARD_PICOCOREMX8ULP */
#ifdef CONFIG_BOARD_OSMSFMX8ULP
		case BT_OSMSFMX8ULP:
			BOARD_InitCANOSM();
			break;
#endif /* CONFIG_BOARD_OSMSFMX8ULP */
#ifdef CONFIG_BOARD_ARMSTONEMX8ULP
		case BT_ARMSTONEMX8ULP:
			BOARD_InitCANArmStone();
			break;
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */
		default:
			break;
	}
}

void BOARD_InitBootPins(struct board_descr *bdescr)
{
	BOARD_InitIOPins(bdescr);
	BOARD_InitLpuartPins(bdescr);
	BOARD_InitI2cPins(bdescr);
	BOARD_InitI2sPins(bdescr);
	BOARD_InitTpmPins(bdescr);
	if (!!(bdescr->bfeatures & (FEAT_QSPI_FLASH | FEAT_QSPI_FLASH)))
		BOARD_InitFLEXSPIPins(bdescr);
	BOARD_InitJTAGPins(bdescr);
	BOARD_InitSPIPins(bdescr);
	BOARD_InitWDOGPins(bdescr);
	BOARD_InitCANPins(bdescr);
}
