/*
 * Copyright (c) 2024 F&S Elektronik Systeme GmbH
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __BOARD_CONFIG_H
#define __BOARD_CONFIG_H

/* remove to disable Board-Support */
#define CONFIG_BOARD_PICOCOREMX8ULP
#define CONFIG_BOARD_OSMSFMX8ULP
#define CONFIG_BOARD_ARMSTONEMX8ULP

#ifdef CONFIG_BOARD_PICOCOREMX8ULP

#define PCORE_UART_B_IFACEID		0
#define PCORE_UART_D_IFACEID		1

#define PCORE_GPIOA_GPIO_J2_33		8
#define PCORE_GPIOA_I2C_RTD_IRQ_B	9
#define PCORE_GPIOA_I2C_B_IRQ_B		18
#define PCORE_GPIOA_SPI_B_CS		19
#define PCORE_GPIOA_PMIC_IRQ_B		24
#define PCORE_GPIOB_GPIO_J2_84		0
#define PCORE_GPIOB_GPIO_J2_86		1
#define PCORE_GPIOB_GPIO_J2_88		2
#define PCORE_GPIOB_GPIO_J2_90		3
#define PCORE_GPIOB_GPIO_J2_92		4
#define PCORE_GPIOB_GPIO_J2_94		5
#define PCORE_GPIOB_GPIO_J2_96		6
#define PCORE_GPIOB_GPIO_J2_98		12
#define PCORE_GPIOB_GPIO_J2_100		13
#define PCORE_GPIOB_GPIO_J2_77		14
#define PCORE_GPIOB_GPIO_J2_79		15
#define PCORE_GPIOC_GPIO_J1_88		0
#define PCORE_GPIOC_GPIO_J2_65		2
#define PCORE_GPIOC_LVDS_CONV_RST	3
#define PCORE_GPIOC_GPIO_J2_67		5
#define PCORE_GPIOC_GPIO_J2_69		6
#define PCORE_GPIOC_GPIO_J2_31		11
#define PCORE_GPIOC_GPIO_J2_60		23

/* If no QSPI is used */
#define PCORE_GPIOC_GPIO_J2_58		12
#define PCORE_GPIOC_GPIO_J2_56		13
#define PCORE_GPIOC_GPIO_J2_87		14
#define PCORE_GPIOC_GPIO_J2_89		15
#define PCORE_GPIOC_GPIO_J2_83		16
#define PCORE_GPIOC_GPIO_J1_64		17
#define PCORE_GPIOC_GPIO_J1_70		18
#define PCORE_GPIOC_GPIO_J1_82		19
#define PCORE_GPIOC_GPIO_J1_95		20
#define PCORE_GPIOC_GPIO_J1_66		21
#define PCORE_GPIOC_GPIO_J1_68		22
#endif

#if defined(CONFIG_BOARD_OSMSFMX8ULP) || defined(CONFIG_BOARD_ARMSTONEMX8ULP)
#define GPIOA_CARRIER_PWR_EN 1
#define GPIOB_CARRIER_PWR_EN 4
#endif

#if defined(CONFIG_BOARD_OSMSFMX8ULP)
#define OSM_GPIOA_GPIO_B_3  0
#define OSM_GPIOA_GPIO_B_4  24
#define OSM_GPIOA_CARRIER_PWR_EN    GPIOA_CARRIER_PWR_EN
#define OSM_GPIOB_GPIO_B_1  5
#define OSM_GPIOB_GPIO_B_2  6
#define OSM_GPIOB_CAM_EN    13
#define OSM_GPIOB_CAM_RST   14
#define OSM_GPIOB_PMIC_IRQ  15
#define OSM_GPIOC_GPIO_A_0  0
#define OSM_GPIOC_GPIO_A_1  3
#define OSM_GPIOC_GPIO_A_2  11
#define OSM_GPIOC_GPIO_A_3  13
#define OSM_GPIOC_GPIO_A_4  14
#define OSM_GPIOC_GPIO_A_5  15
#endif

#if defined(CONFIG_BOARD_ARMSTONEMX8ULP)
#define ASTONE_GPIOB_CARRIER_PWR_EN GPIOB_CARRIER_PWR_EN
#define ASTONE_GPIOC_WLAN_BT_EN     0
#define ASTONE_GPIOC_BT_WAKE_HOST   14
#define ASTONE_GPIOC_BT_WAKE_DEV    15
#define ASTONE_GPIOC_WM8904_IRQ     16
#endif /* CONFIG_BOARD_ARMSTONEMX8ULP */

/* Default settings */
#define GPIOA_NUM 25
#define GPIOB_NUM 16
#define GPIOC_NUM 25

#define OSM_USE_FLEXSPI0
#define PCore_USE_FLEXSPI0

#ifndef CONFIG_I2C_MUTEX_TAKE_MS
#define CONFIG_I2C_MUTEX_TAKE_MS 100
#endif

#define CONFIG_BOARD_I2C_DEFAULT_BAUD      400000U
#define CONFIG_BOARD_I3C_DEFAULT_BAUD      400000U

#ifndef CONFIG_BOARD_LPI2C0_BAUDRATE_HZ
#define CONFIG_BOARD_LPI2C0_BAUDRATE_HZ    CONFIG_BOARD_I2C_DEFAULT_BAUD
#endif

#ifndef CONFIG_BOARD_LPI2C1_BAUDRATE_HZ
#define CONFIG_BOARD_LPI2C1_BAUDRATE_HZ    CONFIG_BOARD_I2C_DEFAULT_BAUD
#endif

#ifndef CONFIG_BOARD_LPI2C2_BAUDRATE_HZ
#define CONFIG_BOARD_LPI2C2_BAUDRATE_HZ    CONFIG_BOARD_I2C_DEFAULT_BAUD
#endif

#ifndef CONFIG_BOARD_LPI2C3_BAUDRATE_HZ
#define CONFIG_BOARD_LPI2C3_BAUDRATE_HZ    CONFIG_BOARD_I2C_DEFAULT_BAUD
#endif

#ifndef CONFIG_BOARD_I3C0_BAUDRATE_HZ
#define CONFIG_BOARD_I3C0_BAUDRATE_HZ    CONFIG_BOARD_I3C_DEFAULT_BAUD
#endif

#ifndef CONFIG_BOARD_I3C1_BAUDRATE_HZ
#define CONFIG_BOARD_I3C1_BAUDRATE_HZ    CONFIG_BOARD_I3C_DEFAULT_BAUD
#endif

#ifndef I3C_RETRY_TIMES
#define I3C_RETRY_TIMES 5000
#endif

#ifndef CONFIG_RGPIO_INTERRUPT_SEL
#define CONFIG_RGPIO_INTERRUPT_SEL kRGPIO_InterruptOutput2
#endif

#ifndef CONFIG_GPIO_INT_PRIO
#define CONFIG_GPIO_INT_PRIO (5U)
#endif

#ifndef CONFIG_GPIOA_IFACEID
#define CONFIG_GPIOA_IFACEID 0
#endif

#ifndef CONFIG_GPIOB_IFACEID
#define CONFIG_GPIOB_IFACEID 1
#endif

#ifndef CONFIG_GPIOC_IFACEID
#define CONFIG_GPIOC_IFACEID 2
#endif

// #define CONFIG_TIMEOUT_WAKEUP_MCORE
// #define CONFIG_TIMEOUT_WAKEUP_SEC 10

#endif /* __BOARD_CONFIG_H */